export const RSS_CATEGORIES = [
    {url: "/api/rss/tintuctrongngay.rss", category: "Tin tức"},
    {url: "/api/rss/bongda.rss", category: "Bóng đá"},
    {url: "/api/rss/asiancup2019.rss", category: "Asian Cup"},
    {url: "/api/rss/anninhhinhsu.rss", category: "An ninh"},
    {url: "/api/rss/thoitrang.rss", category: "Thời trang"},
    {url: "/api/rss/thoitranghitech.rss", category: "Hi-tech"},
    {url: "/api/rss/taichinhbatdongsan.rss", category: "Kinh doanh"},
    {url: "/api/rss/amthuc.rss", category: "Ẩm thực"},
    {url: "/api/rss/lamdep.rss", category: "Làm đẹp"},
    {url: "/api/rss/phim.rss", category: "Phim"},
    {url: "/api/rss/giaoducduhoc.rss", category: "Giáo dục"},
    {url: "/api/rss/bantrecuocsong.rss", category: "Bạn trẻ"},
    {url: "/api/rss/canhacmtv.rss", category: "Ca nhạc"},
    {url: "/api/rss/thethao.rss", category: "Thể thao"},
    {url: "/api/rss/phithuongkyquac.rss", category: "Phi thường"},
    {url: "/api/rss/congnghethongtin.rss", category: "Công nghệ"},
    {url: "/api/rss/oto.rss", category: "Ô tô"},
    {url: "/api/rss/thitruongtieudung.rss", category: "Thị trường"},
    {url: "/api/rss/dulich.rss", category: "Du lịch"},
    {url: "/api/rss/suckhoedoisong.rss", category: "Sức khỏe"},
    {url: "/api/rss/cuoi24h.rss", category: "Cười"},
] as const;

export const CATEGORY_URL_MAP: Record<string, string> = {
    "Tin tức": "/api/rss/tintuctrongngay.rss",
    "Bóng đá": "/api/rss/bongda.rss",
    "Asian Cup": "/api/rss/asiancup2019.rss",
    "An ninh": "/api/rss/anninhhinhsu.rss",
    "Thời trang": "/api/rss/thoitrang.rss",
    "Hi-tech": "/api/rss/thoitranghitech.rss",
    "Kinh doanh": "/api/rss/taichinhbatdongsan.rss",
    "Ẩm thực": "/api/rss/amthuc.rss",
    "Làm đẹp": "/api/rss/lamdep.rss",
    "Phim": "/api/rss/phim.rss",
    "Giáo dục": "/api/rss/giaoducduhoc.rss",
    "Bạn trẻ": "/api/rss/bantrecuocsong.rss",
    "Ca nhạc": "/api/rss/canhacmtv.rss",
    "Thể thao": "/api/rss/thethao.rss",
    "Phi thường": "/api/rss/phithuongkyquac.rss",
    "Công nghệ": "/api/rss/congnghethongtin.rss",
    "Ô tô": "/api/rss/oto.rss",
    "Thị trường": "/api/rss/thitruongtieudung.rss",
    "Du lịch": "/api/rss/dulich.rss",
    "Sức khỏe": "/api/rss/suckhoedoisong.rss",
    "Cười": "/api/rss/cuoi24h.rss",
};
